<?php

namespace FriendsOfRedaxo\Podcastmanager\Statistics;

/**
 * AWStats Statistics Provider
 * 
 * Parses text reports generated by AWStats
 * Format: awstats.YYYYMM.domain.txt
 */
class AwstatsProvider extends StatisticsProvider {
    
    /**
     * Get statistics for a specific month/year
     * 
     * @param string $month Month (MM format)
     * @param string $year Year (YYYY format)
     * @return StatisticsData Statistics data object
     */
    public function getStatistics($month, $year) {
        $filename = $this->getFilename($month, $year);
        
        if (!file_exists($filename)) {
            throw new \Exception("AWStats report not found: {$filename}");
        }
        
        $data = new StatisticsData($month, $year, $this->getProviderName());
        $parsed = $this->parseTextReport($filename);
        
        if ($parsed) {
            $data->set('raw_data', $parsed);
            $data->setVisits($parsed['visits'] ?? 0);
            $data->setHits($parsed['hits'] ?? 0);
            $data->setBandwidth($parsed['bandwidth'] ?? 0);
            $data->setPages($parsed['pages'] ?? 0);
            $data->setBots($parsed['bots'] ?? 0);
            $data->setFailedRequests($parsed['failed_requests'] ?? 0);
        }
        
        return $data;
    }
    
    /**
     * Get available months for statistics
     * 
     * @return array Array of available months ['2024-01', '2024-02', ...]
     */
    public function getAvailableMonths() {
        $months = [];
        
        if (!is_dir($this->basePath)) {
            return $months;
        }
        
        $files = glob($this->basePath . '/awstats.*.txt');
        
        foreach ($files as $file) {
            if (preg_match('/awstats\.(\d{4})(\d{2})\./', basename($file), $matches)) {
                $year = $matches[1];
                $month = $matches[2];
                $months[] = $year . '-' . $month;
            }
        }
        
        rsort($months);
        return array_unique($months);
    }
    
    /**
     * Get provider name for display
     */
    public function getProviderName() {
        return 'AWStats';
    }
    
    /**
     * Get filename for specific month/year
     * 
     * Tries multiple naming conventions:
     * - awstats.YYYYMM.domain.txt
     * - awstats.YYYYMM.txt
     * 
     * @param string $month Month (MM format)
     * @param string $year Year (YYYY format)
     * @return string Full path to report file
     */
    protected function getFilename($month, $year) {
        // First try with domain suffix
        $filename = $this->basePath . '/awstats.' . $year . $month . '.' . str_replace('.', '_', $this->domain) . '.txt';
        if (file_exists($filename)) {
            return $filename;
        }
        
        // Then try without domain suffix
        $filename = $this->basePath . '/awstats.' . $year . $month . '.txt';
        if (file_exists($filename)) {
            return $filename;
        }
        
        // Return the first variant as default
        return $this->basePath . '/awstats.' . $year . $month . '.' . str_replace('.', '_', $this->domain) . '.txt';
    }
    
    /**
     * Parse AWStats text report
     * 
     * @param string $filename Path to text file
     * @return array Parsed data
     */
    protected function parseTextReport($filename) {
        $lines = file($filename, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        $data = [];
        
        foreach ($lines as $line) {
            // AWStats format: KEY VALUE
            if (strpos($line, ' ') === false || $line[0] === '#') {
                continue;
            }
            
            list($key, $value) = explode(' ', trim($line), 2);
            
            switch ($key) {
                case 'TotalVisits':
                    $data['visits'] = (int)$value;
                    break;
                case 'TotalHits':
                    $data['hits'] = (int)$value;
                    break;
                case 'TotalPages':
                    $data['pages'] = (int)$value;
                    break;
                case 'TotalBandwidth':
                    $data['bandwidth'] = (int)$value;
                    break;
                case 'TotalBots':
                    $data['bots'] = (int)$value;
                    break;
                case 'TotalNotFound':
                    $data['failed_requests'] = (int)$value;
                    break;
            }
        }
        
        return $data;
    }
}
