<?php

namespace FriendsOfRedaxo\Podcastmanager\Statistics;

/**
 * Webalizer Statistics Provider
 * 
 * Parses HTML reports generated by Webalizer
 * Format: usage_YYYYMM.html
 */
class WebalizerProvider extends StatisticsProvider {
    
    /**
     * Get statistics for a specific month/year
     * 
     * @param string $month Month (MM format)
     * @param string $year Year (YYYY format)
     * @return StatisticsData Statistics data object
     */
    public function getStatistics($month, $year) {
        $filename = $this->getFilename($month, $year);
        
        if (!file_exists($filename)) {
            throw new \Exception("Webalizer report not found: {$filename}");
        }
        
        $data = new StatisticsData($month, $year, $this->getProviderName());
        $parsed = $this->parseHtmlReport($filename);
        
        if ($parsed) {
            $data->set('raw_data', $parsed);
            $data->setVisits($parsed['visits'] ?? 0);
            $data->setHits($parsed['hits'] ?? 0);
            $data->setBandwidth($parsed['bandwidth'] ?? 0);
            $data->setPages($parsed['pages'] ?? 0);
            $data->setBots($parsed['bots'] ?? 0);
            $data->setFailedRequests($parsed['failed_requests'] ?? 0);
        }
        
        return $data;
    }
    
    /**
     * Get available months for statistics
     * 
     * @return array Array of available months ['2024-01', '2024-02', ...]
     */
    public function getAvailableMonths() {
        $months = [];
        
        if (!is_dir($this->basePath)) {
            return $months;
        }
        
        $files = glob($this->basePath . '/usage_*.html');
        
        foreach ($files as $file) {
            if (preg_match('/usage_(\d{4})(\d{2})\.html/', basename($file), $matches)) {
                $year = $matches[1];
                $month = $matches[2];
                $months[] = $year . '-' . $month;
            }
        }
        
        rsort($months);
        return array_unique($months);
    }
    
    /**
     * Get provider name for display
     */
    public function getProviderName() {
        return 'Webalizer';
    }
    
    /**
     * Get filename for specific month/year
     * 
     * @param string $month Month (MM format)
     * @param string $year Year (YYYY format)
     * @return string Full path to report file
     */
    protected function getFilename($month, $year) {
        return $this->basePath . '/usage_' . $year . $month . '.html';
    }
    
    /**
     * Parse Webalizer HTML report
     * 
     * @param string $filename Path to HTML file
     * @return array Parsed data
     */
    protected function parseHtmlReport($filename) {
        $content = file_get_contents($filename);
        $data = [];
        
        // Create DOM document to parse HTML
        $doc = new \DOMDocument();
        $previous = libxml_use_internal_errors(true);
        $doc->loadHTML($content);
        libxml_use_internal_errors($previous);
        
        $xpath = new \DOMXPath($doc);
        
        // Find statistics in table rows
        // Webalizer structure: specific row numbers contain key metrics
        
        // Get summary statistics - typically in row 7 (Bandwidth)
        // Row structure varies, so we look for patterns
        
        $tables = $xpath->query('//table');
        foreach ($tables as $table) {
            $rows = $xpath->query('.//tr', $table);
            
            foreach ($rows as $idx => $row) {
                $cells = $xpath->query('.//td|.//th', $row);
                if ($cells->length >= 2) {
                    $label = trim($cells->item(0)->textContent);
                    $value = trim($cells->item(1)->textContent);
                    
                    // Extract numeric values and match to known fields
                    if (stripos($label, 'Visits') !== false) {
                        $data['visits'] = $this->parseNumber($value);
                    }
                    if (stripos($label, 'Hits') !== false) {
                        $data['hits'] = $this->parseNumber($value);
                    }
                    if (stripos($label, 'Pages') !== false) {
                        $data['pages'] = $this->parseNumber($value);
                    }
                    if (stripos($label, 'Bandwidth') !== false) {
                        $data['bandwidth'] = $this->parseBandwidth($value);
                    }
                    if (stripos($label, 'Bots') !== false) {
                        $data['bots'] = $this->parseNumber($value);
                    }
                    if (stripos($label, 'Failed Requests') !== false) {
                        $data['failed_requests'] = $this->parseNumber($value);
                    }
                }
            }
        }
        
        return $data;
    }
    
    /**
     * Parse number from string (remove commas, etc.)
     * 
     * @param string $str Number string
     * @return int Parsed number
     */
    protected function parseNumber($str) {
        return (int)preg_replace('/[^0-9]/', '', $str);
    }
    
    /**
     * Parse bandwidth string to bytes
     * 
     * Supports formats like:
     * - "2.5 GB"
     * - "512 MB"
     * - "1024 KB"
     * 
     * @param string $str Bandwidth string
     * @return int Number of bytes
     */
    protected function parseBandwidth($str) {
        preg_match('/([0-9.]+)\s*([KMGT]?B)/i', $str, $matches);
        
        if (!isset($matches[1])) {
            return 0;
        }
        
        $size = (float)$matches[1];
        $unit = strtoupper($matches[2] ?? 'B');
        
        $multipliers = [
            'B' => 1,
            'KB' => 1024,
            'MB' => 1024 ** 2,
            'GB' => 1024 ** 3,
            'TB' => 1024 ** 4,
        ];
        
        return (int)($size * ($multipliers[$unit] ?? 1));
    }
}
